version: 2

sources:
  - name: raw_data
    description: "Raw data sources for NYC taxi rides"
    database: taxi_rides_ny
    schema: prod
    tables:
      - name: yellow_tripdata
      - name: green_tripdata